<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Ambulance.aspx.cs" Inherits="ER_application.Web_Forms.Ambulance" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link rel="stylesheet" href="~/CSS/Ambulance.css"/>
    <%--<script type="text/javascript" src="http://maps.google.com/maps/api/js"></script>--%>
    <%--<script type="text/javascript" src="http://www.geocodezip.com/scripts/v3_epoly.js"></script>--%>
    <script type="text/javascript" src="/Scripts/jquery-2.2.1.min.js"></script>
    

<%--    <script type="text/javascript" src="/Scripts/createMarker.js"></script>--%>
</head>
<body>
    <form id="form1" runat="server">
    <div id="welcome" runat="server">
    
    </div>
    <table id="myTable">
	    <tr>
			<th class="header" id="dispatchMenu"> Dispatch </th>
			<th class="header" id="patientMenu"> Patient info </th>
			<th class="header" id="problemMenu"> Problem </th>
			<th class="header" id="vitalMenu"> Vital signs </th>
			<th class="header" id="interventionsMenu"> Interventions </th>
		</tr>
	</table>
	<div id="dispatchDiv">
		<table id="dispatchTable">
			<tr>
				<th> Location </th>
				<td id="loc"> locatia </td>
			</tr>
			<tr>
				<th> Caller name </th>
				<td> caller </td>
			</tr>
			<tr>
				<th> Description </th>
				<td> description </td>
			</tr>
		</table>
	</div>
	<div id="patientDiv">
		<table id="patientTable">
			<tr>
				<th> First name </th>
				<td> First name </td>
				<th> Last name </th>
				<td> Last name </td>
			</tr>
			<tr>
				<th> Birthdate </th>
				<td> Birthdate </td>
				<th> Age </th>
				<td> Age </td>
			</tr>
			<tr>
				<th> Gender </th>
				<td> Gender </td>
				<th> Blood type </th>
				<td> Blood type </td>
			</tr>
			<tr>
				<th> Last name </th>
				<td> Last name </td>
			</tr>
			<tr>
				<th> Last name </th>
				<td> Last name </td>
			</tr>
		</table>
		<button id="patientButton"> Send </button>
	</div>
    <asp:Button class="addPatient" ID="Add" runat="server" Text="Add patient" onclick="btn_Add_Click"></asp:Button><br/> 
    <asp:Button class="updatePatient" ID="Update" runat="server" Text="Update patient"></asp:Button><br/>   

    <div>
        <div id="sendInfo">
            <div class="container">
                <input type="text" id="message" />
                <input type="button" id="sendmessage" value="Send" />
                <input type="hidden" id="displayname" />
                <ul id="discussion"></ul>
            </div>

        </div>
    
    </div>
                <div id="map_canvas" style="width:50%;height:500px;"></div>

    </form>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="/Scripts/jquery-1.10.2.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="/Scripts/jquery.signalR-2.0.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>
    <script src='<%: ResolveClientUrl("~/signalr/hubs") %>'></script>
    <script src="/Scripts/Ambulance.js" "></script>
    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">


        var username = '<%= Session["userName"] %>';
        //var myMarker = null;
        //var i = 0;

        //var marker = null;
        //infowindow = new google.maps.InfoWindow(
        //  {
        //      size: new google.maps.Size(150, 50)
        //  });

        //var myOptions = {
        //    zoom: 10,
        //    mapTypeId: google.maps.MapTypeId.ROADMAP
        //}
        //map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

        //address = 'Strada Hermann Oberth 5, Cluj-Napoca'
        //geocoder = new google.maps.Geocoder();
        //geocoder.geocode({ 'address': address }, function (results, status) {
        //    map.fitBounds(results[0].geometry.viewport);
        //});

        //google.maps.event.addListener(map, 'click', function () {
        //    infowindow.close();
        //});

        //google.maps.event.addListener(map, 'click', function (event) {
        //        if (marker) {
        //            marker.setPosition(event.latLng);
        //        } else {
        //            marker = new google.maps.Marker({
        //                position: event.latLng,
        //                map: map
        //            });
        //        }
        //        myMarker = event.latLng;
        //    //placeMarker(event.latLng);
        //    alert(myMarker.toString());
        //    //var chat = $.connection.chatHub;
        //    //$.connection.hub.start().done(function () {
        //    //    //Call the Send method on the hub.
        //      //  chat.server.send(username, event.latLng);
        //    //    //Clear text box and reset focus for next comment.
        //        //$('#patientState').val('').focus();
        //    //});
        //});

        $(function () {

            // Declare a proxy to reference the hub.
            var chat = $.connection.chatHub;
            //// Create a function that the hub can call to broadcast messages.
            chat.client.receive = function (name, message, toWho) {
                if (toWho == username) {
                    alert(name + " " + message + " " + toWho);
                }
                else
                    alert("not to me");
                //alert(message);
                //$('#loc').html(message);
            };
            // Get the user name and store it to prepend to messages.
            //$('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.
            //$('#patientState').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#Update').click(function () {
                    //chat.server.send(username, myMarker.toString());
                    //chat.server.send(username, myMarker.toString() + "_" + $('#patientState').val());
                    patient = {
                        firstName: "Jon",
                        lastName: "Snow",
                        ssn: "123",
                        birthDate: "02/02/1999"
                    };
                    //alert("gheo");
                    chat.server.update(username, patient);
                    // Call the Send method on the hub.
                    // Clear text box and reset focus for next comment.
                    //$('#patientState').val('').focus();
                });
                //$('#Add').click(function () {
                //    //chat.server.send(username, myMarker.toString());
                //    chat.server.send(username, myMarker.toString() + "_" + $('#firstName').val());
                //    // Call the Send method on the hub.
                //    // Clear text box and reset focus for next comment.
                //    $('#firstName').val('').focus();
                //});
                chat.client.receive = function (name, message, toWho) {
                    if (toWho == username) {
                        alert(name + " " + message + " " + toWho);
                    }
                    else
                        alert("not to me");
                   // $('#loc').html(message);
                };
            });
        });
       // initialize();
        //function initialize() {

        //    var marker = null;
        //    infowindow = new google.maps.InfoWindow(
        //      {
        //          size: new google.maps.Size(150, 50)
        //      });

        //    var myOptions = {
        //        zoom: 10,
        //        mapTypeId: google.maps.MapTypeId.ROADMAP
        //    }
        //    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

        //    address = 'Strada Hermann Oberth 5, Cluj-Napoca'
        //    geocoder = new google.maps.Geocoder();
        //    geocoder.geocode({ 'address': address }, function (results, status) {
        //        map.fitBounds(results[0].geometry.viewport);
        //    });

        //    google.maps.event.addListener(map, 'click', function () {
        //        infowindow.close();
        //    });
        //}

        //var marker;

        //function placeMarker(location) {
        //    if (marker) {
        //        marker.setPosition(location);
        //    } else {
        //        marker = new google.maps.Marker({
        //            position: location,
        //            map: map
        //        });
        //    }
        //}

        //google.maps.event.addListener(map, 'click', function (event) {
        //    placeMarker(event.latLng);
        //    alert(event.latLng);
        //    var chat = $.connection.chatHub;
        //    $.connection.hub.start().done(function () {
        //        //Call the Send method on the hub.
        //        chat.server.send("amb1", event.latLng);
        //        //Clear text box and reset focus for next comment.
        //        //$('#patientState').val('').focus();
        //    });
        //});

       
        //$(document).ready(function () {
       
        //Add.Attributes.Add("onclick", " this.disabled = true; " + ClientScript.GetPostBackEventReference(btnSave, null) + ";");

        //document.getElementById("Update").disabled = true;
        
        //$('#Add').click(function () {
        //    document.getElementById("Add").disabled = true;
        //    document.getElementById("Update").disabled = false;
        //});

            //});
  
    </script>
</body>
</html>
