<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Dispatch.aspx.cs" Inherits="ER_application.Web_Forms.ER" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link rel="stylesheet" href="~/CSS/Dispatch.css"/>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js"></script>
    <script type="text/javascript" src="http://www.geocodezip.com/scripts/v3_epoly.js"></script>
    <script type="text/javascript" src="/Scripts/jquery-2.2.1.min.js"></script>
<%--    <script type="text/javascript" src="/Scripts/mapScript.js"></script>--%>
    <%--<script type="text/javascript" src="/Scripts/ajax.js" ></script>--%>
</head>

<body>
   <form id="form1" runat="server">
    <div>
        <div id="welcome" runat="server">

        </div>

        <table id="topMenu">
			<tr>
                <th class="hide"> </th>
				<th class="show" id="dispatch">Dispatch</th>
				<th class="hide"> </th>
			</tr>
		</table>

        <div id="callDiv">
            <p>Apeluri nepreluate</p>
            <table id="callTable"> </table>
        </div>

        <div id="infoCall">
        <div id="divCall">
            <button id="btnWait">Pune in asteptare</button>
            <button id="btnEndCall">Inchide apelul</button>
        </div>
        </div>
        <div id="mapCall"> </div>

        <div id="divAmb">
            <ul id="listAmb">
            </ul>
        </div>
        <div id="map_canvas" style="width:100%;height:500px;"></div>

    </div>
    </form>
   <!--Script references. -->
   <!--Reference the jQuery library. -->
    <script src="/Scripts/Dispatch.js" "></script>
    <script src="/Scripts/jquery-1.10.2.min.js" "></script>
    <!--Reference the SignalR library. -->
    <script src="/Scripts/jquery.signalR-2.0.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src='<%: ResolveClientUrl("~/signalr/hubs") %>'></script>
</body>
</html>
