<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ER.aspx.cs" Inherits="ER_application.Web_Forms.UPU" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>UPU</title>
    <link rel="stylesheet" href="~/CSS/ER.css"/>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js"></script>
    <script type="text/javascript" src="http://www.geocodezip.com/scripts/v3_epoly.js"></script>
    <script type="text/javascript" src="/Scripts/jquery-2.2.1.min.js"></script>
    
    <script src="/Scripts/ERScripts/ER_Functions.js"></script>

</head>
<body>
    <form id="form1" runat="server">
    <div id="welcome" runat="server">
    
    </div>
    <div id="divAmb">
        <ul id="ulAmb"></ul>
    </div>
    <table id="myTable">
	    <tr>
            <th class="header" id="ambulanceMenu"> Ambulante </th>
			<th class="header" id="patientMenu"> Pacient </th>
			<th class="header" id="vitalMenu"> Functii vitale </th>
			<th class="header" id="interventionsMenu"> Interventii </th>
		</tr>
	</table>
    <div id="patientDiv">
	</div>
    <div id="problemDiv">
	    <%--<div id="injuryPb">
            <p id="pInjury">Presenting problem</p>
		    <ul id="ulInjuries"></ul>
		</div>
        <div id="mechanism">
            <p id="pMechanism"> Mechanism of injury</p>
            <ul id="ulMechanism"></ul>
        </div>--%>
	</div>
    <div id="vitalDiv"></div>
    <div id="mapCall"> </div>
    </form>
    <script src="/Scripts/jquery-1.10.2.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="/Scripts/jquery.signalR-2.0.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>
    <script src='<%: ResolveClientUrl("~/signalr/hubs") %>'></script>
    <script src="/Scripts/ERScripts/ER.js"></script>
    <script type="text/javascript">

        $(function () {

            // Declare a proxy to reference the hub.
            var chat = $.connection.chatHub;
            $.connection.hub.start().done(function () {
            });
        });
    
    </script>
</body>
</html>
