//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER_application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbulanceType
    {
        public AmbulanceType()
        {
            this.Ambulance = new HashSet<Ambulance>();
        }
    
        public int ambulanceTypeID { get; set; }
        public string typeName { get; set; }
    
        public virtual ICollection<Ambulance> Ambulance { get; set; }
    }
}
