//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER_application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disease
    {
        public Disease()
        {
            this.PatientDisease = new HashSet<PatientDisease>();
        }
    
        public int diseaseID { get; set; }
        public string name { get; set; }
        public Nullable<int> categoryID { get; set; }
        public string history { get; set; }
    
        public virtual DiseaseCategory DiseaseCategory { get; set; }
        public virtual ICollection<PatientDisease> PatientDisease { get; set; }
    }
}
