//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER_application.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EREntities : DbContext
    {
        public EREntities()
            : base("name=EREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allergy> Allergy { get; set; }
        public virtual DbSet<Ambulance> Ambulance { get; set; }
        public virtual DbSet<AmbulanceType> AmbulanceType { get; set; }
        public virtual DbSet<AmbulanceUser> AmbulanceUser { get; set; }
        public virtual DbSet<Disease> Disease { get; set; }
        public virtual DbSet<DiseaseCategory> DiseaseCategory { get; set; }
        public virtual DbSet<DispatchUser> DispatchUser { get; set; }
        public virtual DbSet<ER_User> ER_User { get; set; }
        public virtual DbSet<Incident> Incident { get; set; }
        public virtual DbSet<Injury> Injury { get; set; }
        public virtual DbSet<InjuryMechanism> InjuryMechanism { get; set; }
        public virtual DbSet<Mechanism> Mechanism { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<PatientAmbulance> PatientAmbulance { get; set; }
        public virtual DbSet<PatientDisease> PatientDisease { get; set; }
        public virtual DbSet<PatientInjury> PatientInjury { get; set; }
        public virtual DbSet<PatientVital> PatientVital { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserMode> UserMode { get; set; }
        public virtual DbSet<VitalSign> VitalSign { get; set; }
    }
}
