//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER_application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public Incident()
        {
            this.PatientAmbulance = new HashSet<PatientAmbulance>();
        }
    
        public int incidentID { get; set; }
        public Nullable<System.DateTime> dateOfEvent { get; set; }
        public string address { get; set; }
        public string callerLocation { get; set; }
        public string callerPhone { get; set; }
        public string callerName { get; set; }
        public string locationGPS { get; set; }
        public string patientLocation { get; set; }
        public string patientState { get; set; }
        public string patientInfo { get; set; }
        public string description { get; set; }
        public Nullable<int> resolved { get; set; }
    
        public virtual ICollection<PatientAmbulance> PatientAmbulance { get; set; }
    }
}
