//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER_application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InjuryMechanism
    {
        public int imID { get; set; }
        public Nullable<int> paID { get; set; }
        public Nullable<int> mecID { get; set; }
    
        public virtual Mechanism Mechanism { get; set; }
        public virtual PatientAmbulance PatientAmbulance { get; set; }

        public InjuryMechanism(int paID, int mecID)
        {
            this.paID = paID;
            this.mecID = mecID;
        }

        public InjuryMechanism() { }
    }
}
