//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER_application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mechanism
    {
        public Mechanism()
        {
            this.InjuryMechanism = new HashSet<InjuryMechanism>();
        }
    
        public int mechanismID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<InjuryMechanism> InjuryMechanism { get; set; }
    }
}
