//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER_application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientIntervention
    {
        public int piID { get; set; }
        public Nullable<int> paID { get; set; }
        public string intName { get; set; }
        public string intType { get; set; }
        public Nullable<int> intNumber { get; set; }
        public Nullable<int> intHour { get; set; }
        public Nullable<int> intMin { get; set; }
        public string intSupport { get; set; }
    
        public virtual PatientAmbulance PatientAmbulance { get; set; }
    }
}
