//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER_application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInjury
    {
        public int piID { get; set; }
        public Nullable<int> paID { get; set; }
        public Nullable<int> injID { get; set; }
    
        public virtual Injury Injury { get; set; }
        public virtual PatientAmbulance PatientAmbulance { get; set; }
    }
}
