//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER_application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAmbulance
    {
        public int patientID { get; set; }
        public int ambulanceID { get; set; }
        public int incidentID { get; set; }
    
        public virtual Ambulance Ambulance { get; set; }
        public virtual Incident Incident { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
