//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER_application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDisease
    {
        public int pID { get; set; }
        public int dID { get; set; }
        public Nullable<System.DateTime> diagnosedDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual Patient Patient { get; set; }

        public PatientDisease(int pID, int dID)
        {
            this.pID = pID;
            this.dID = dID;
        }
    }
}
