//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER_application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVital
    {
        public int pvID { get; set; }
        public Nullable<int> paID { get; set; }
        public Nullable<int> vID { get; set; }
    
        public virtual PatientAmbulance PatientAmbulance { get; set; }
        public virtual VitalSign VitalSign { get; set; }
    }
}
