//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ER_application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMode
    {
        public UserMode()
        {
            this.AmbulanceUser = new HashSet<AmbulanceUser>();
            this.DispatchUser = new HashSet<DispatchUser>();
            this.ER_User = new HashSet<ER_User>();
        }
    
        public int userID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> role { get; set; }
    
        public virtual ICollection<AmbulanceUser> AmbulanceUser { get; set; }
        public virtual ICollection<DispatchUser> DispatchUser { get; set; }
        public virtual ICollection<ER_User> ER_User { get; set; }
    }
}
